### ISSUE TITLE
Social links don't show up in Safari

### ISSUE THREAD

**Issue by irace** [irace/prospectheightsbk.com#32]
Haven't been able to figure it out yet

**Comment by irace** [comment]
@nicbarajas Any idea on this one? I tried figuring it out for a while but am at a bit of a loss

**Comment by irace** [comment]
This magically seems fixed

**Comment by nicbarajas** [comment]
Huh, wonder what happened here? I could never recreate it locally anyway, and had meant to reach out for examples.
