### ISSUE TITLE
Filters for business type

### ISSUE THREAD

**Issue by irace** [irace/prospectheightsbk.com#4]
Suggestion from @brianpartridge: ability to filter by bar, restaurant, coffee shop, etc.

I also like the idea of filtering by delivery or pick-up, and maybe criteria like: serves, sells gift cards, has a donation fund, enables you to pay over the phone, etc.

Haven't fully thought through how I might implement this but have some ideas. You could add tags to the YAML file which you’d add as CSS classes at Liquid templating time. Then, your filters would add/remove CSS rules to hide/show certain classes.

**Comment by nicbarajas** [comment]
Going to close this since #39 has nice improvements for type on the page. If we want more we can re-raise.
